name: fluhub
description: A GitHub app.
version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: '^0.1.2'
  dio: ^2.1.5
  flutter_markdown: ^0.2.0
  graphql_flutter: ^1.0.1
  shared_preferences: ^0.5.2
  flutter_webview_plugin: ^0.3.5
  redux: ^3.0.0
  flutter_redux: ^0.5.3
  redux_thunk: ^0.2.1
  redux_epics: ^0.10.6
  bloc: ^0.14.4
  flutter_bloc: ^0.20.0
  equatable: ^0.3.0
  url_launcher: ^5.1.0
  webview_flutter: ^0.3.10+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
