name: fluhub
description: A GitHub app.
version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^2.1.5
  flutter_markdown: ^0.2.0
  flutter_redux: ^0.5.3
  graphql_flutter: ^1.0.1
  rxdart: ^0.22.0
  shared_preferences: ^0.5.2
  webview_flutter: ^0.3.9+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false
