name: fluhub
description: A GitHub app.
version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dio: ^3.0.4
  flutter_markdown: ^0.3.0
  graphql_flutter: ^3.0.0-beta.3
  shared_preferences: ^0.5.4
  flutter_webview_plugin: ^0.3.8
  redux: ^3.0.0
  flutter_redux: ^0.5.4
  bloc: ^3.0.0
  flutter_bloc: ^3.1.0
  equatable: ^1.0.0
  url_launcher: ^5.1.2
  webview_flutter: ^0.3.15
  flutter_emoji: ^2.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
